[tool.black]
line-length = 120           # NOTE: in sync with ruff
target-version = ['py39']   # NOTE: in sync with ruff
verbose = false
diff = false
color = false
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
