[tool.black]
line-length = 120 # in sync with ruff
target-version = ['py39']
verbose = false
diff = false
color = false
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.mypy]
python_version = 3.9  # Specify the Python version used
ignore_missing_imports = true
disallow_untyped_defs = false
disable_error_code = ['override', 'attr-defined']
disallow_any_generics = false

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra" # -ra -q
testpaths = [
    "tests",
    # "tests/unit",
    # "tests/integration",
    # "tests/system",
]
filterwarnings = "ignore::DeprecationWarning" # ignore deprecation warnings when running tests
