name: "Continuous Integration (CI)"
description: "DevOps: Run CI checks on pull requests and pushes to main branch."
inputs:
  working-directory:
    description: "Directory to change to before running checks."
    required: false
    default: "."
  ruff-output-filename:
    description: "File to write Ruff output to."
    required: false
    default: "ruff_results.log"
  isort-output-filename:
    description: "File to write isort output to."
    required: false
    default: "isort_results.log"
  black-output-filename:
    description: "File to write Black output to."
    required: false
    default: "black_results.log"
  mypy-output-filename:
    description: "File to write MyPy output to."
    required: false
    default: "mypy_results.log"
  unit-test-output-filename:
    description: "File to write unit test output to."
    required: false
    default: "unit_test_results.log"
runs:
  using: "composite"
  steps:
    - name: Run Isort Formatter Check
      run: |
        cd ${{ inputs.working-directory }} || exit 1
        curl -sSL https://raw.githubusercontent.com/gao-hongnan/omniverse/continuous-integration/scripts/devops/continuous-integration/format_isort.sh -o format_isort.sh
        chmod +x format_isort.sh
        bash format_isort.sh | tee ${{ inputs.isort-output-filename }}
      shell: bash
      if: always()
    - name: Run Black Formatter Check
      run: |
        cd ${{ inputs.working-directory }} || exit 1
        curl -sSL https://raw.githubusercontent.com/gao-hongnan/omniverse/continuous-integration/scripts/devops/continuous-integration/format_black.sh -o format_black.sh
        chmod +x format_black.sh
        bash format_black.sh | tee ${{ inputs.black-output-filename }}
      shell: bash
      if: always()
    - name: Run Linter Check
      run: |
        cd ${{ inputs.working-directory }} || exit 1
        curl -sSL https://raw.githubusercontent.com/gao-hongnan/omniverse/continuous-integration/scripts/devops/continuous-integration/lint_ruff.sh -o lint_ruff.sh
        chmod +x lint_ruff.sh
        bash lint_ruff.sh | tee ${{ inputs.ruff-output-filename }}
      shell: bash
      if: always()
    - name: Run Type Checker Check
      run: |
        cd ${{ inputs.working-directory }} || exit 1
        curl -sSL https://raw.githubusercontent.com/gao-hongnan/omniverse/continuous-integration/scripts/devops/continuous-integration/type_mypy.sh -o type_mypy.sh
        chmod +x type_mypy.sh
        bash type_myph.sh | tee ${{ inputs.mypy-output-filename }}
      shell: bash
      if: always()
    - name: Run Unit Tests
      run: |
        cd ${{ inputs.working-directory }} || exit 1
        curl -sSL https://raw.githubusercontent.com/gao-hongnan/omniverse/continuous-integration/scripts/devops/continuous-integration/test_unit_pytest.sh -o test_unit_pytest.sh
        chmod +x test_unit_pytest.sh
        bash test_unit_pytest.sh | tee ${{ inputs.unit-test-output-filename }}
      shell: bash
      if: always()
    - name: Upload Checked Results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: continuous-integration-result-logs
        path: |
          ${{ inputs.working-directory }}/${{ inputs.isort-output-filename }}
          ${{ inputs.working-directory }}/${{ inputs.black-output-filename }}
          ${{ inputs.working-directory }}/${{ inputs.ruff-output-filename }}
          ${{ inputs.working-directory }}/${{ inputs.mypy-output-filename }}
          ${{ inputs.working-directory }}/${{ inputs.unit-test-output-filename }}

