name: "Continuous Integration (CI)"

on:
  workflow_call:
    inputs:
      working-directory:
        description: "Directory to change to before running checks."
        required: true
        type: string
        default: "."
      ruff-script-location:
        description: "Location of Ruff script to run."
        required: false
        type: string
        default: "scripts/devops/continuous-integration/lint_ruff.sh"
      ruff-output-filename:
        description: "File to write Ruff output to."
        required: false
        type: string
        default: "ruff_results.log"
      isort-script-location:
        description: "Location of isort script to run."
        required: false
        type: string
        default: "scripts/devops/continuous-integration/format_isort.sh"
      isort-output-filename:
        description: "File to write isort output to."
        required: false
        type: string
        default: "isort_results.log"
      black-script-location:
        description: "Location of Black script to run."
        required: false
        type: string
        default: "scripts/devops/continuous-integration/format_black.sh"
      black-output-filename:
        description: "File to write Black output to."
        required: false
        type: string
        default: "black_results.log"
      mypy-script-location:
        description: "Location of MyPy script to run."
        required: false
        type: string
        default: "scripts/devops/continuous-integration/type_mypy.sh"
      mypy-output-filename:
        description: "File to write MyPy output to."
        required: false
        type: string
        default: "mypy_results.log"
      unit-test-script-location:
        description: "Location of unit test script to run."
        required: false
        type: string
        default: "scripts/devops/continuous-integration/test_unit_pytest.sh"
      unit-test-output-filename:
        description: "File to write unit test output to."
        required: false
        type: string
        default: "unit_test_results.log"

env:
  WORKING_DIRECTORY: ${{ inputs.working-directory == '' && '.' || inputs.working-directory }}

jobs:
  continuous-integration:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.9]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip" # caching pip will speed up installs
      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies
        with:
          working-directory: ${{ env.WORKING_DIRECTORY }}
      - name: Run Continuous Integration Action
        uses: ./.github/actions/continuous-integration
        with:
          working-directory: ${{ env.WORKING_DIRECTORY }}
          ruff-script-location: ${{ inputs.ruff-script-location }}
          ruff-output-filename: ${{ inputs.ruff-output-filename }}
          isort-script-location: ${{ inputs.isort-script-location }}
          isort-output-filename: ${{ inputs.isort-output-filename }}
          black-script-location: ${{ inputs.black-script-location }}
          black-output-filename: ${{ inputs.black-output-filename }}
          mypy-script-location: ${{ inputs.mypy-script-location }}
          mypy-output-filename: ${{ inputs.mypy-output-filename }}
          unit-test-script-location: ${{ inputs.unit-test-script-location }}
          unit-test-output-filename: ${{ inputs.unit-test-output-filename }}
