name: continuous-integration-omnivault

on:
  push:
    branches:
      - main
      - dev
      - continuous-integration
    paths:
      - ".github/**/*"
      - ".ruff.toml"
      - "pyproject.toml"
      - "scripts/**/*"
      - "omnivault/**"
      - "!omnivault/**/*.md"
      - "!omnivault/**/.gitignore"
  pull_request:
    branches:
      - main
    paths:
      - "omnivault/**"
      - "!omnivault/**/*.md"
      - "!omnivault/**/.gitignore"

# cancel any previous runs that are still in progress if a new one is queued.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env: # FIXME: env cannot be passed down to jobs defined as workflow call what?! https://github.com/orgs/community/discussions/26671 - this is annoying.
  WORKING_DIRECTORY: "."
  RUFF_SCRIPT_LOCATION: "scripts/devops/continuous-integration/lint_ruff.sh"
  RUFF_OUTPUT_FILENAME: "ruff_results.log"
  BLACK_SCRIPT_LOCATION: "scripts/devops/continuous-integration/format_black.sh"
  BLACK_OUTPUT_FILENAME: "black_results.log"
  MYPY_SCRIPT_LOCATION: "scripts/devops/continuous-integration/type_mypy.sh"
  MYPY_OUTPUT_FILENAME: "mypy_results.log"
  UNIT_TEST_SCRIPT_LOCATION: "scripts/devops/continuous-integration/test_unit_pytest.sh"
  UNIT_TEST_OUTPUT_FILENAME: "unit_test_results.log"

jobs:
  setup-env-vars:
    runs-on: ubuntu-latest
    outputs:
      working-directory: ${{ env.WORKING_DIRECTORY }}
      ruff-script-location: ${{ env.RUFF_SCRIPT_LOCATION }}
      ruff-output-filename: ${{ env.RUFF_OUTPUT_FILENAME }}
      black-script-location: ${{ env.BLACK_SCRIPT_LOCATION }}
      black-output-filename: ${{ env.BLACK_OUTPUT_FILENAME }}
      mypy-script-location: ${{ env.MYPY_SCRIPT_LOCATION }}
      mypy-output-filename: ${{ env.MYPY_OUTPUT_FILENAME }}
      unit-test-script-location: ${{ env.UNIT_TEST_SCRIPT_LOCATION }}
      unit-test-output-filename: ${{ env.UNIT_TEST_OUTPUT_FILENAME }}
    steps:
      - run: echo "Exposing env vars to reusable workflows."
  continuous-integration:
    needs: setup-env-vars
    uses: ./.github/workflows/_continuous_integration.yaml
    with:
      working-directory: ${{ needs.setup-env-vars.outputs.working-directory }}
      ruff-script-location: ${{ needs.setup-env-vars.outputs.ruff-script-location }}
      ruff-output-filename: ${{ needs.setup-env-vars.outputs.ruff-output-filename }}
      black-script-location: ${{ needs.setup-env-vars.outputs.black-script-location }}
      black-output-filename: ${{ needs.setup-env-vars.outputs.black-output-filename }}
      mypy-script-location: ${{ needs.setup-env-vars.outputs.mypy-script-location }}
      mypy-output-filename: ${{ needs.setup-env-vars.outputs.mypy-output-filename }}
      unit-test-script-location: ${{ needs.setup-env-vars.outputs.unit-test-script-location }}
      unit-test-output-filename: ${{ needs.setup-env-vars.outputs.unit-test-output-filename }}
    secrets: inherit