name: "Continuous Integration Checks on Omnivault."

on:
  push:
    branches:
      - main
      - continuous-integration
    paths:
      - ".github/**/*"
      - ".ruff.toml"
      - "pyproject.toml"
      - "scripts/**/*"
      - "omnivault/**"
      - "!omnivault/**/*.md"
      - "!omnivault/**/.gitignore"
  pull_request:
    branches:
      - main
      - continuous-integration
    paths:
      - "omnivault/**"
      - "!omnivault/**/*.md"
      - "!omnivault/**/.gitignore"

# cancel any previous runs that are still in progress if a new one is queued.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env: # FIXME: env cannot be passed down to jobs what?! https://github.com/orgs/community/discussions/26671
  WORKING_DIRECTORY: "."
  RUFF_SCRIPT_LOCATION: "scripts/devops/continuous-integration/lint_ruff.sh"
  RUFF_OUTPUT_FILENAME: "ruff_results.log"
  BLACK_SCRIPT_LOCATION: "scripts/devops/continuous-integration/format_black.sh"
  BLACK_OUTPUT_FILENAME: "black_results.log"
  MYPY_SCRIPT_LOCATION: "scripts/devops/continuous-integration/type_mypy.sh"
  MYPY_OUTPUT_FILENAME: "mypy_results.log"

jobs:
  continuous-integration:
    uses: ./.github/workflows/_continuous_integration.yaml
    with:
      working-directory: "."
      ruff-script-location: "scripts/devops/continuous-integration/lint_ruff.sh"
      ruff-output-filename: "ruff_results.log"
      black-script-location: "scripts/devops/continuous-integration/format_black.sh"
      black-output-filename: "black_results.log"
      mypy-script-location: "scripts/devops/continuous-integration/type_mypy.sh"
      mypy-output-filename: "mypy_results.log"
    secrets: inherit