name: "Continuous Integration Checks on Omnivault."

on:
  push:
    branches:
      - main
      - continuous-integration
    paths:
      - "omnivault/**"
      - "!omnivault/**/*.md"
      - "!omnivault/**/.gitignore"
  pull_request:
    branches:
      - main
      - continuous-integration
    paths:
      - "omnivault/**"
      - "!omnivault/**/*.md"
      - "!omnivault/**/.gitignore"

# cancel any previous runs that are still in progress if a new one is queued.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  WORKING-DIRECTORY: ${{ inputs.working-directory == '' && '.' || inputs.working-directory }}
  RUFF-SCRIPT-LOCATION: "scripts/devops/continuous-integration/lint_ruff.sh"
  RUFF-OUTPUT-FILENAME: "ruff_results.log"

jobs:
  continuous-integration:
    uses: ./.github/workflows/_continuous_integration.yaml
    with:
      working-directory: ${{ env.WORKING-DIRECTORY }}
      ruff-script-location: ${{ env.RUFF-SCRIPT-LOCATION }}
      ruff-output-filename: ${{ env.RUFF-OUTPUT-FILENAME }}
    secrets: inherit